"""Deployment output per candidate: deployment.yaml (pools, workers, GPUs) and, for EPD
topologies, a vLLM-native launch script. AIConfigurator's generator skips EPD rows
("the generator bridge does not map the dedicated encode pool yet"), so this fills that part.

Flags follow vLLM examples/disaggregated/disaggregated_encoder at main 3ee2906f47 (2026-09-23):
encoder tiers on other nodes use ECCPUConnector with ec_enable_nixl (needs VLLM_USE_V2_MODEL_RUNNER=1
and the nixl package); prefill->decode uses NixlConnector; disagg_epd_proxy.py fronts it all.
"""
import os
import re

import yaml

VLLM_PIN = "vllm main 3ee2906f47 (2026-09-23)"

LAUNCH = r'''#!/usr/bin/env bash
# {title}
# Generated by mm-sizer for bucket pool {bucket} ({share:.0%} of requests). Flags pinned to {pin}.
# Run one role per node:  ROLE=encode|{lang_roles}|proxy ./launch.sh
# Workers in this pool: {counts}
# Encoder GPUs: {enc_sys}. Language GPUs: {main_sys}.
set -euo pipefail
MODEL=${{MODEL:-{model}}}
PORT=${{PORT:-8100}}
EC_BYTES=${{EC_BYTES:-{ec_bytes}}}          # CPU-tier bytes for encoder outputs (>= in-flight embeddings)
EC='{{"ec_connector": "ECCPUConnector", "ec_role": "ROLE", "ec_connector_extra_config": {{"ec_enable_nixl": true, "ec_cpu_bytes": '$EC_BYTES'}}}}'
MMK='{mm_kwargs}'
export VLLM_USE_V2_MODEL_RUNNER=1

case "${{ROLE:?set ROLE}}" in
encode)
  # one encoder instance per GPU; ec_producer implies mm_encoder_only
  for g in $(seq 0 $(( ${{GPUS_PER_NODE:-1}} - 1 ))); do
    CUDA_VISIBLE_DEVICES=$g vllm serve "$MODEL" --port $((PORT + g)) \
      --tensor-parallel-size {enc_tp} --no-enable-prefix-caching --enable-request-id-headers \
      --max-num-batched-tokens {enc_batched} --mm-processor-kwargs "$MMK" \
      --ec-transfer-config "${{EC/ROLE/ec_producer}}" &
  done ;;
{lang_cases}
proxy)
  python disagg_epd_proxy.py --host 0.0.0.0 --port ${{PROXY_PORT:-10001}} \
    --encode-servers-urls "${{ENCODE_URLS:?comma-separated encode URLs}}" \
{proxy_lang}    ;;
esac
wait
'''

AGG_CASE = r'''agg)
  vllm serve "$MODEL" --port "$PORT" --tensor-parallel-size {tp} --enable-request-id-headers \
    --max-num-seqs {conc} --max-model-len {max_len} --mm-processor-kwargs "$MMK" \
    --ec-transfer-config "${{EC/ROLE/ec_consumer}}" ;;'''

PD_CASES = r'''prefill)
  vllm serve "$MODEL" --port "$PORT" --tensor-parallel-size {ptp} --enable-request-id-headers \
    --max-model-len {max_len} --mm-processor-kwargs "$MMK" \
    --ec-transfer-config "${{EC/ROLE/ec_consumer}}" \
    --kv-transfer-config '{{"kv_connector": "NixlConnector", "kv_role": "kv_producer"}}' ;;
decode)
  vllm serve "$MODEL" --port "$PORT" --tensor-parallel-size {dtp} --enable-request-id-headers \
    --max-num-seqs {conc} --max-model-len {max_len} \
    --kv-transfer-config '{{"kv_connector": "NixlConnector", "kv_role": "kv_consumer"}}' ;;'''


def _parse(shape):
    """'P:2xtp1pp1... D:1xtp2... E:4xtp1' -> {P: (2, 1), D: (1, 2), E: (4, 1)}"""
    out = {}
    for part in shape.split():
        k, v = part.split(":", 1)
        m = re.match(r"(\d+)x(?:tp)?(\d+)?", v)
        out[k] = (int(m.group(1)), int(m.group(2) or 1)) if m else (1, 1)
    return out


def mm_kwargs(plan):
    img = plan["request_plan"].get("image", {})
    if "max_pixels" not in img:
        return "{}"
    return '{"size": {"longest_edge": %d, "shortest_edge": %d}}' % (img["max_pixels"], img.get("min_pixels", 65536))


def write(cand, buckets, plan, cfg, bytes_per_token, outdir):
    os.makedirs(outdir, exist_ok=True)
    bk = {b["id"]: b for b in buckets}
    pools = (cand.get("online") or cand.get("batch") or {}).get("pools")
    dep = {"topology": cand["topology"], "main_system": cand["main"], "encoder_system": cand["encoder"],
           "serving": VLLM_PIN if cand["topology"] in ("e_agg", "e_p_d") else "see AIConfigurator artifacts",
           "routing": "route each request to the pool of its bucket (by visual tokens)" if len(buckets) > 1 else None,
           "pools": []}
    for bid, row in cand["per_bucket"].items():
        s = bk[bid]["shape"]
        dep["pools"].append({"bucket": bid, "share": round(bk[bid]["weight"], 4), "replicas": (pools or {}).get(bid),
                             "replica_shape": row["shape"], "replica_gpus": row["gpus"], "seq_per_s_per_replica": row["seq_s"],
                             "max_visual_tokens": s["visual_tokens"], "concurrency": row["concurrency"]})
        if cand["topology"] not in ("e_agg", "e_p_d"):
            continue
        p = _parse(row["shape"])
        e_n, e_tp = p.get("E", (1, 1))
        # every request in the bucket must fit, not just the representative one
        max_len = bk[bid].get("max_prompt_tokens", s["visual_tokens"] + s["isl"]) + bk[bid].get("max_out_tokens", s["osl"]) + 256
        # embeddings live in the CPU tier only between encode and prefill: buffer ~64 requests, 1-32 GiB
        ec_bytes = min(32 << 30, max(1 << 30, 64 * s["visual_tokens"] * bytes_per_token["embedding"]))
        if cand["topology"] == "e_agg":
            a_n, a_tp = p.get("A", (1, 1))
            cases = AGG_CASE.format(tp=a_tp, conc=row["concurrency"], max_len=max_len)
            proxy = '    --decode-servers-urls "${DECODE_URLS:?agg instance URLs}"\n'
            counts, roles = f"encode {e_n} x tp{e_tp}, agg {a_n} x tp{a_tp}", "agg"
        else:
            (p_n, p_tp), (d_n, d_tp) = p.get("P", (1, 1)), p.get("D", (1, 1))
            cases = PD_CASES.format(ptp=p_tp, dtp=d_tp, conc=row["concurrency"], max_len=max_len)
            proxy = ('    --prefill-servers-urls "${PREFILL_URLS:?prefill URLs}" \\\n'
                     '    --decode-servers-urls "${DECODE_URLS:?decode URLs}"\n')
            counts, roles = f"encode {e_n} x tp{e_tp}, prefill {p_n} x tp{p_tp}, decode {d_n} x tp{d_tp}", "prefill|decode"
        script = LAUNCH.format(title=f"{cand['topology']} on {cand['main']} with {cand['encoder']} encoders",
                               bucket=bid, share=bk[bid]["weight"], pin=VLLM_PIN, lang_roles=roles, counts=counts,
                               enc_sys=cand["encoder"], main_sys=cand["main"], model=plan["model"], ec_bytes=ec_bytes,
                               mm_kwargs=mm_kwargs(plan), enc_tp=e_tp, enc_batched=max(16384, s["visual_tokens"] * 2),
                               lang_cases=cases, proxy_lang=proxy)
        path = os.path.join(outdir, f"launch_{bid.replace('+', '_')}.sh")
        open(path, "w").write(script)
        os.chmod(path, 0o755)
    yaml.safe_dump(dep, open(os.path.join(outdir, "deployment.yaml"), "w"), sort_keys=False)
    return outdir
